FROM python:3.9
WORKDIR /app
COPY dashboard-motorbike.py requirements.txt carlita.jpg ./
RUN pip install --no-cache-dir -r requirements.txt
CMD ["streamlit", "run", "dashboard-motorbike.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
